Samsung/CredData

- README.md
For better understanding of the table of performance metrics, I suggest to add 'terminology' under the benchmark result.
If the terminology is not accurate, please make it clear. :)
> Update 'readme.md' to add terminology of performance metrics

- meta/23689bd1.csv
Remove assumed FP from dataset
Based on the only change in prediction from https://github.com/Samsung/CredSweeper/pull/184
> Remove FP in 23689bd1.csv

- .github/workflows/test.yml
- requirements.txt
- run.sh
- set the action for every 6 days to prevent cache pruning
> Apply git cache for benchmark

- meta/798d34aa.csv
- meta/8ba59c91.csv
- meta/a0abd87c.csv
- meta/e3377359.csv
There are 8 credit card numbers were found in the data set
According https://github.com/Samsung/CredSweeper/pull/267
> Markup for credit card numbers

- meta/e3377359.csv
3 credentials found look like Jira2FA tokens 
for https://github.com/Samsung/CredSweeper/pull/311
> Credentials look like Jira2FA tokens

- meta/387016a6.csv
- meta/6482c382.csv
- meta/7529016f.csv
- meta/894e3377.csv
- meta/a0cd6261.csv
- meta/b356a0cd.csv
- meta/bcb18a48.csv
- meta/c9b945fa.csv
- meta/ec138349.csv
for https://github.com/Samsung/CredSweeper/pull/362
> Bitbucket markup

- benchmark/scanner/scanner.py
- meta/387016a6.csv
- meta/533c47c6.csv
- meta/69d49010.csv
- meta/894e3377.csv
- meta/fdbe07ac.csv
> Openssh private keys markup

- benchmark/common/result.py
- benchmark/scanner/credsweeper.py
- benchmark/scanner/scanner.py
- benchmark/scanner/true_false_counter.py
- requirements.txt
- Skip install unused packages
- meta is loaded once in list to reduce disc reading
- refactoring report output in table view
- refactoring and optimisation
based on #41 
new report looks like:
```
DATA: 19434458 valid lines. MARKUP: 73692 items
Category                      Positives    Negatives    Template
--------------------------  -----------  -----------  ----------
Authentication Key & Token           67            1          31
Generic Secret                     1055           15         203
Generic Token                       333           45         558
Other                               511        63135         635
Password                           1403          110        4170
Predefined Pattern                  326            2          40
Private Key …
```
> Tabulated benchmark result

- meta/7738e44d.csv
markup for https://github.com/Samsung/CredSweeper/pull/406
> Missed VIN markup

- meta/c9b945fa.csv
- Lost credential markup added
> lost auth signature markup added

- meta/a0cd6261.csv
- meta/f623c7b3.csv
missed markup for string definition  u"xxxxx"
> missed markup

- meta/57154bcf.csv
- meta/8ba59c91.csv
- snapshot.yaml
- fix wrong FileId according previous markup
- touched snapshot.yaml to refresh benchmark cache
- test: https://github.com/Samsung/CredSweeper/pull/458
> Markup fix

- meta/0f133e09.csv
- meta/6a132a15.csv
- meta/a09d9e50.csv
- meta/cc51a2f0.csv
- snapshot.yaml
- Markup for credentials which have been not found before due line size limitation (2000).
> Markup for long lines

- meta/efb4b495.csv
- meta/f623c7b3.csv
> two url password renamed

- download_data.py
- use single commit fetching - decreases from 11 to 2 min time for download (verification: https://github.com/Samsung/CredSweeper/pull/509)
- skip some debug messages
> Single commit fetch mode

- meta/110f8d35.csv
- meta/d2926eb1.csv
- meta/e3377359.csv
- meta/eab0f8ed.csv
- snapshot.yaml
> markup for private keys

- meta/6a132a15.csv
- meta/6ab520fe.csv
- meta/ffea718f.csv
> markup for oversized lines

- meta/0fc802c8.csv
- meta/69d49010.csv
- meta/7c7558cf.csv
- 3x password casses
- 2x templates for .tfvars
> 3 missed markup

- meta/2ba83c6a.csv
- meta/2e665fa9.csv
- meta/349ac2b1.csv
- meta/387016a6.csv
- meta/55031e17.csv
- meta/60f9915d.csv
- meta/6c73b80a.csv
- meta/784d78e8.csv
- meta/7f0408de.csv
- meta/80815938.csv
- meta/81cd05d0.csv
- meta/894e3377.csv
- meta/a09d9e50.csv
- meta/b081551c.csv
- meta/d93c01fb.csv
- meta/f295f04f.csv
some values become true during obfuscation
> correction

- download_data.py
- meta/106c7cd2.csv
- meta/16fc0238.csv
- meta/255bae6f.csv
- meta/2ba83c6a.csv
- meta/2e6b3af5.csv
- meta/4a8d3fd4.csv
- meta/6d59a88a.csv
- meta/891ea546.csv
- meta/8ba59c91.csv
- meta/8cda00f3.csv
- meta/a8bdca79.csv
- meta/b8d8b8c3.csv
- meta/d93c01fb.csv
- meta/e3377359.csv
- meta/ec869dbc.csv
- fix some positions for creds
- fix obfuscation for slack, some 'base64:...."
- add markup for multiple credentials in one line
> multicred in line for new ml

- review_data.py
line ending leads for many changes in the diff
> Update review data script for multiline markup

- download_data.py
- meta/894e3377.csv
- meta/ffea718f.csv
- skip obfuscation for some parts which are well-known and requires for the credential type
> Obfuscation enchancement

- .github/workflows/review.yml
- meta_cred.py
- meta_row.py
- review_data.py
- cache usage
- review output improvement
- CredSweeper benchmark test: https://github.com/Samsung/CredSweeper/actions/runs/9041864830?pr=545 (BM works, but scores were not changed by this PR)
> [CI] improvements

- meta/6a132a15.csv
- meta/a09d9e50.csv
oversize lines were rescaned and some markupp found
> markup for IP in long lines

- meta/6c73b80a.csv
- meta/a0cd6261.csv
- meta/ac9be8d9.csv
- meta/f295f04f.csv
password = "[dsfku]" were ignored previously
> missed markup with square brackets

- benchmark/scanner/scanner.py
- meta/6c73b80a.csv
- review_data.py
- fix suggestion id generator
- correction for Category password -> URL Credentials (% sign may be in url for escaping a unicode char)
- added check for whole line show - should not contain a markup with start values markup
> URL creds markup

- meta/6a132a15.csv
- meta/6c73b80a.csv
- meta/a09d9e50.csv
for https://github.com/Samsung/CredSweeper/pull/585
> after value sanitiser for \\n

- meta/21867a14.csv
- meta/2ba83c6a.csv
- meta/32f5ea73.csv
- meta/41d10ede.csv
- meta/638eb0c6.csv
- meta/6482c382.csv
- meta/6c73b80a.csv
- meta/6d59a88a.csv
- meta/798d34aa.csv
- meta/a09d9e50.csv
- meta/a0abd87c.csv
- meta/a0cd6261.csv
- meta/a15774b8.csv
- meta/ac9be8d9.csv
- meta/c9b945fa.csv
- meta/d2d68c6f.csv
- meta/d93c01fb.csv
- meta/f295f04f.csv
for https://github.com/Samsung/CredSweeper/pull/588
> corrections markup during ml retrain

- meta/177cf0f9.csv
- meta/6c73b80a.csv
- meta/942d502d.csv
- meta/bcb18a48.csv
- meta/d94d550a.csv
- meta/ef35cd4d.csv
- meta/efb4b495.csv
- meta/f008dd40.csv
- meta/f8f46739.csv
- update_meta.py
BM scores diff in  https://github.com/Samsung/CredSweeper/pull/596/files#diff-6fbc517609be91039970276d1697e0d85c108026521b3978ba0bf955082d2b13
> Auxiliary corrections

- review_data.py
In case of value_start only - apply BRIGHT style to help find begin of the value
> [review workflow] Use BRIGTH style for value_start only

- .ci/benchmark.txt
- markup_report.py
- meta/ec138349.csv
- add 2 False cases found in URL to use as false in training
- use ml_validation instead removed api_validation for report markup
> A couple False markup

- .ci/benchmark.txt
- download_data.py
- meta/eab0f8ed.csv
> salesforce markup

- .github/workflows/review.yml
https://github.com/actions/upload-artifact/releases/tag/v4.6.0
> bump upload-artifact to 4.6.0

- .ci/benchmark.txt
- markup_report.py
- meta/2ba83c6a.csv
- meta/43e1f4ea.csv
- meta/55031e17.csv
- meta/5504e505.csv
- meta/57c424f8.csv
- meta/73ae7ce6.csv
- meta/8ba59c91.csv
- meta/8bc560cd.csv
- meta/8cda00f3.csv
- meta/a09d9e50.csv
- meta/a15774b8.csv
- meta/bbb4193f.csv
- meta/c41bb134.csv
- meta/c9201a51.csv
- meta/d518da13.csv
- meta/f710ac3c.csv
> Markup for retrained model

- .ci/benchmark.txt
- benchmark/scanner/scanner.py
- Refactoring file path processing to extract repo name
- Use all files for integrity - md5sum matches in ml train
> Suggestion and integrity fix

- .ci/benchmark.txt
- meta/90aebe4a.csv
> 90aebe4a markup

- .ci/benchmark.txt
- meta/3808df46.csv
- meta/3adfbe9d.csv
- meta/50366042.csv
- meta/6482c382.csv
- meta/798d34aa.csv
- meta/894e3377.csv
- meta/8f499d55.csv
- meta/a09d9e50.csv
- meta/cecc6b48.csv
- meta/d2d68c6f.csv
- meta/eab0f8ed.csv
- meta/f008dd40.csv
- markup missed true cases of SalesForce creds
- add possible false cases for Bitbucket creds
> Missed saledforce creds

- requirements.txt
- snapshot.yaml
- update owner repo name after renaming
- bump requirements
Diff review cannot be passed due the repo does not exist for old name
> Update snapshot after repo renaming

- .ci/benchmark.txt
- meta/28728ab4.csv
Lost category for the same data
> Hotfix: Missed markup for akamai token

- .ci/benchmark.txt
- meta/1e007c58.csv
- meta/387016a6.csv
- meta/a0cd6261.csv
- meta/a15774b8.csv
- review_data.py
> CURL User Password
